### ISSUE TITLE
Scripts requested via cdn using non https being blocked.

### ISSUE THREAD

**Issue by thejesusbr** [formikaio/HTML5-Genetic-3-wheelers#2]
As a security measure, Chrome is now blocking resources requested by HTTP in pages that use HTTPS. As consequence, some resources (JQuery and bootstrap CSS files) are blocked, resulting in loss of functionality and wrong rendering of the layout.

**Comment by formikaio** [comment]
Updated. Thank you for the feedback!

**Comment by thejesusbr** [comment]
My pleasure!
